version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back
    image: node:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./back:/app
    working_dir: /app
    command: sh -c "npm install && npx prisma migrate deploy && npm run start:dev"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./front
    image: node:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
volumes:
  postgres_data:
